### ISSUE TITLE
🐛 [Bug] Sending e-mail notifications fails if too many mentions

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#6727]
### Problem
No e-mail notifications are sent if too many users are mentioned in a single post or comment. Tested on wir.social with 92 mentions.

### Possible solutions
- Batch job (cron job) - required for #6593 
- For users: Limit the number of mentions per post/comment in the UI. Display an error message if exceeding.

### Error in the backend

> yarn run v1.22.19
> $ node dist/
> Warning: Sentry middleware inactive.
> 🚀 Server ready at http://localhost:4000/
> 🚀 Subscriptions ready at ws://localhost:4000/graphql
> /app/node_modules/nodemailer/lib/smtp-connection/index.js:1199
> this._onError(new Error('Invalid greeting. response=' + str), 'EPROTOCOL', str, 'CONN');
> ^
> 
> Error: Invalid greeting. response=421 4.7.0 mail.webcraft-media.de Error: too many connections from 164.92.142.135: 421 4.7.0 mail.webcraft-media.de Error: too many connections from 164.92.142.135
> at SMTPConnection._actionGreeting (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1199:27)
> at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:942:20)
> at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
> at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
> at TLSSocket.emit (node:events:513:28)
> at TLSSocket.emit (node:domain:489:12)
> at addChunk (node:internal/streams/readable:324:12)
> at readableAddChunk (node:internal/streams/readable:297:9)
> at Readable.push (node:internal/streams/readable:234:10)
> at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
> code: 'EPROTOCOL',
> response: '421 4.7.0 mail.webcraft-media.de Error: too many connections from 164.92.142.135',
> responseCode: 421,
> command: 'CONN'
> }
> 
> Node.js v19.9.0
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

As discussed with @Tirokk

**Comment by sushidave** [comment]
Closed as duplicate of #6726
